"""Initial

Revision ID: 9075ca6ac5b8
Revises: 
Create Date: 2026-09-05 14:58:23.316437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '9075ca6ac5b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('execution_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('plan_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_sessions_id'), 'execution_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_execution_sessions_plan_id'), 'execution_sessions', ['plan_id'], unique=False)
    op.create_table('prediction_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_request_id', sa.Integer(), nullable=False),
    sa.Column('predicted_duration', sa.Float(), nullable=False),
    sa.Column('actual_duration', sa.Float(), nullable=False),
    sa.Column('prediction_error', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('execution_outcome', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_calibrations_id'), 'prediction_calibrations', ['id'], unique=False)
    op.create_table('railway_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_railway_nodes_geometry', 'railway_nodes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_railway_nodes_id'), 'railway_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_railway_nodes_name'), 'railway_nodes', ['name'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('train_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CONTROLLER', 'MAINTENANCE', 'DIVISIONAL', 'MANAGEMENT', 'CREW', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('plan_version', sa.String(), nullable=True),
    sa.Column('previous_plan_id', sa.String(), nullable=True),
    sa.Column('new_plan_id', sa.String(), nullable=True),
    sa.Column('optimizer_version', sa.String(), nullable=True),
    sa.Column('safety_validator_version', sa.String(), nullable=True),
    sa.Column('explanation_version', sa.String(), nullable=True),
    sa.Column('simulation_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('depots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['railway_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_depots_geometry', 'depots', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_depots_id'), 'depots', ['id'], unique=False)
    op.create_table('disruption_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('plan_version', sa.String(), nullable=False),
    sa.Column('affected_request', sa.Integer(), nullable=True),
    sa.Column('affected_section', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_events_id'), 'disruption_events', ['id'], unique=False)
    op.create_table('loops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['railway_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loops_id'), 'loops', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('maintenance_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_assets_geometry', 'maintenance_assets', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_maintenance_assets_id'), 'maintenance_assets', ['id'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('has_canopy', sa.Boolean(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['railway_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_platforms_geometry', 'platforms', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_table('raw_ingestion_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_ingestion_records_id'), 'raw_ingestion_records', ['id'], unique=False)
    op.create_index(op.f('ix_raw_ingestion_records_source_record_id'), 'raw_ingestion_records', ['source_record_id'], unique=False)
    op.create_table('sidings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['railway_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sidings_geometry', 'sidings', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sidings_id'), 'sidings', ['id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('plan_version', sa.String(), nullable=False),
    sa.Column('block_request_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('gang_id', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('elapsed_minutes', sa.Float(), nullable=True),
    sa.Column('expected_remaining_minutes', sa.Float(), nullable=True),
    sa.Column('actual_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_table('track_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('gradient', sa.Float(), nullable=False),
    sa.Column('curve_radius', sa.Float(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['railway_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['railway_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_track_sections_geometry', 'track_sections', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_track_sections_id'), 'track_sections', ['id'], unique=False)
    op.create_table('train_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['railway_nodes.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_schedules_id'), 'train_schedules', ['id'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['maintenance_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_id'), 'defects', ['id'], unique=False)
    op.create_table('fusion_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.Enum('DUPLICATE', 'MISSING_VALUE', 'CONTRADICTION', 'STALE', 'OVERDUE', name='issuetype'), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_ingestion_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_issues_id'), 'fusion_issues', ['id'], unique=False)
    op.create_table('level_crossings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_manned', sa.Boolean(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_level_crossings_geometry', 'level_crossings', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_level_crossings_id'), 'level_crossings', ['id'], unique=False)
    op.create_table('maintenance_gangs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_gangs_id'), 'maintenance_gangs', ['id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['maintenance_assets.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False)
    op.create_table('provenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('selected_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_ingestion_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_logs_entity_id'), 'provenance_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_provenance_logs_entity_type'), 'provenance_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_provenance_logs_id'), 'provenance_logs', ['id'], unique=False)
    op.create_table('traction_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_section_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traction_states_id'), 'traction_states', ['id'], unique=False)
    op.create_table('tsrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_section_id', sa.Integer(), nullable=False),
    sa.Column('speed_limit', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tsrs_id'), 'tsrs', ['id'], unique=False)
    op.create_table('block_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_requests_id'), 'block_requests', ['id'], unique=False)
    op.drop_table('tract')
    op.drop_index('idx_tiger_county', table_name='county')
    op.drop_table('county')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('countyns', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('cntyidfp', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lsad', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('classfp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('csafp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('cbsafp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('metdivfp', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('cntyidfp', name='pk_tiger_county'),
    sa.UniqueConstraint('gid', name='uidx_county_gid')
    )
    op.create_index('idx_tiger_county', 'county', ['countyfp'], unique=False)
    op.create_table('tract',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('countyfp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('tractce', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('tract_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('namelsad', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mtfcc', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('funcstat', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('aland', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('awater', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intptlat', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('intptlon', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL", name='enforce_geotype_geom'),
    sa.CheckConstraint('st_ndims(the_geom) = 2', name='enforce_dims_geom'),
    sa.CheckConstraint('st_srid(the_geom) = 4269', name='enforce_srid_geom'),
    sa.PrimaryKeyConstraint('tract_id', name='tract_pkey')
    )
    op.drop_index(op.f('ix_block_requests_id'), table_name='block_requests')
    op.drop_table('block_requests')
    op.drop_index(op.f('ix_tsrs_id'), table_name='tsrs')
    op.drop_table('tsrs')
    op.drop_index(op.f('ix_traction_states_id'), table_name='traction_states')
    op.drop_table('traction_states')
    op.drop_index(op.f('ix_provenance_logs_id'), table_name='provenance_logs')
    op.drop_index(op.f('ix_provenance_logs_entity_type'), table_name='provenance_logs')
    op.drop_index(op.f('ix_provenance_logs_entity_id'), table_name='provenance_logs')
    op.drop_table('provenance_logs')
    op.drop_index(op.f('ix_maintenance_requests_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_maintenance_gangs_id'), table_name='maintenance_gangs')
    op.drop_table('maintenance_gangs')
    op.drop_index(op.f('ix_level_crossings_id'), table_name='level_crossings')
    op.drop_index('idx_level_crossings_geometry', table_name='level_crossings', postgresql_using='gist')
    op.drop_table('level_crossings')
    op.drop_index(op.f('ix_fusion_issues_id'), table_name='fusion_issues')
    op.drop_table('fusion_issues')
    op.drop_index(op.f('ix_defects_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_train_schedules_id'), table_name='train_schedules')
    op.drop_table('train_schedules')
    op.drop_index(op.f('ix_track_sections_id'), table_name='track_sections')
    op.drop_index('idx_track_sections_geometry', table_name='track_sections', postgresql_using='gist')
    op.drop_table('track_sections')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_sidings_id'), table_name='sidings')
    op.drop_index('idx_sidings_geometry', table_name='sidings', postgresql_using='gist')
    op.drop_table('sidings')
    op.drop_index(op.f('ix_raw_ingestion_records_source_record_id'), table_name='raw_ingestion_records')
    op.drop_index(op.f('ix_raw_ingestion_records_id'), table_name='raw_ingestion_records')
    op.drop_table('raw_ingestion_records')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_index('idx_platforms_geometry', table_name='platforms', postgresql_using='gist')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_maintenance_assets_id'), table_name='maintenance_assets')
    op.drop_index('idx_maintenance_assets_geometry', table_name='maintenance_assets', postgresql_using='gist')
    op.drop_table('maintenance_assets')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_loops_id'), table_name='loops')
    op.drop_table('loops')
    op.drop_index(op.f('ix_disruption_events_id'), table_name='disruption_events')
    op.drop_table('disruption_events')
    op.drop_index(op.f('ix_depots_id'), table_name='depots')
    op.drop_index('idx_depots_geometry', table_name='depots', postgresql_using='gist')
    op.drop_table('depots')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_railway_nodes_name'), table_name='railway_nodes')
    op.drop_index(op.f('ix_railway_nodes_id'), table_name='railway_nodes')
    op.drop_index('idx_railway_nodes_geometry', table_name='railway_nodes', postgresql_using='gist')
    op.drop_table('railway_nodes')
    op.drop_index(op.f('ix_prediction_calibrations_id'), table_name='prediction_calibrations')
    op.drop_table('prediction_calibrations')
    op.drop_index(op.f('ix_execution_sessions_plan_id'), table_name='execution_sessions')
    op.drop_index(op.f('ix_execution_sessions_id'), table_name='execution_sessions')
    op.drop_table('execution_sessions')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
